### PR TITLE
Only strip prefixMatcher when qualifier

### LINKED ISSUE #546: Function code intellisense bug and add one additional charachter at start of function name
# Version

4.6.0

# Description

I wrote a module (Test) with a function name echo and then i want to use echo function. when i type Test.e and want to select echo from code intellisense this bug occur and also in editor typed eecho (one additional e at start function name). 

```elixir
defmodule Test do
  def echo do
    Test.e<caret>
  end
end
```

# Exception

## Message

chars sequence.length:102, start:102, end:103

## Stacktrace

```
java.lang.IndexOutOfBoundsException: chars sequence.length:102, start:102, end:103
	at com.intellij.util.text.CharSequenceSubSequence.<init>(CharSequenceSubSequence.java:34)
	at com.intellij.util.text.ImmutableText.subSequence(ImmutableText.java:232)
	at com.intellij.openapi.editor.impl.DocumentImpl$5.compute(DocumentImpl.java:838)
	at com.intellij.openapi.editor.impl.DocumentImpl$5.compute(DocumentImpl.java:835)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:888)
	at com.intellij.openapi.editor.impl.DocumentImpl.getText(DocumentImpl.java:835)
	at org.elixir_lang.code_insight.completion.insert_handler.CallDefinitionClause.handleInsert(CallDefinitionClause.java:25)
	at com.intellij.codeInsight.lookup.LookupElementBuilder.handleInsert(LookupElementBuilder.java:389)
	at com.intellij.codeInsight.completion.CodeCompletionHandlerBase.lambda$insertItem$6(CodeCompletionHandlerBase.java:670)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWriteAction(ApplicationImpl.java:927)
	at com.intellij.codeInsight.completion.CodeCompletionHandlerBase.insertItem(CodeCompletionHandlerBase.java:660)
	at com.intellij.codeInsight.completion.CodeCompletionHandlerBase.access$200(CodeCompletionHandlerBase.java:69)
	at com.intellij.codeInsight.completion.CodeCompletionHandlerBase$2.perform(CodeCompletionHandlerBase.java:596)
	at com.intellij.openapi.editor.impl.CaretModelImpl.lambda$runForEachCaret$2(CaretModelImpl.java:355)
	at com.intellij.openapi.editor.impl.CaretModelImpl.doWithCaretMerging(CaretModelImpl.java:444)
	at com.intellij.openapi.editor.impl.CaretModelImpl.runForEachCaret(CaretModelImpl.java:347)
	at com.intellij.openapi.editor.impl.CaretModelImpl.runForEachCaret(CaretModelImpl.java:338)
	at com.intellij.codeInsight.completion.CodeCompletionHandlerBase.insertItemHonorBlockSelection(CodeCompletionHandlerBase.java:584)
	at com.intellij.codeInsight.completion.CodeCompletionHandlerBase.lookupItemSelected(CodeCompletionHandlerBase.java:554)
	at com.intellij.codeInsight.completion.CompletionProgressIndicator.itemSelected(CompletionProgressIndicator.java:175)
	at com.intellij.codeInsight.completion.CompletionLookupArranger.itemSelected(CompletionLookupArranger.java:173)
	at com.intellij.codeInsight.lookup.impl.LookupImpl.fireItemSelected(LookupImpl.java:821)
	at com.intellij.codeInsight.lookup.impl.LookupImpl.finishLookup(LookupImpl.java:510)
	at com.intellij.codeInsight.lookup.impl.LookupImpl.finishLookup(LookupImpl.java:455)
	at com.intellij.codeInsight.lookup.impl.actions.ChooseItemAction$Handler.execute(ChooseItemAction.java:81)
	at com.intellij.openapi.editor.actionSystem.EditorActionHandler.doExecute(EditorActionHandler.java:172)
	at com.intellij.openapi.editor.actionSystem.EditorActionHandler$4.perform(EditorActionHandler.java:217)
	at com.intellij.openapi.editor.actionSystem.EditorActionHandler.doIfEnabled(EditorActionHandler.java:109)
	at com.intellij.openapi.editor.actionSystem.EditorActionHandler.execute(EditorActionHandler.java:214)
	at com.intellij.openapi.editor.actionSystem.EditorAction.lambda$actionPerformed$0(EditorAction.java:95)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:149)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:109)
	at com.intellij.openapi.editor.actionSystem.EditorAction.actionPerformed(EditorAction.java:104)
	at com.intellij.openapi.editor.actionSystem.EditorAction.actionPerformed(EditorAction.java:83)
	at com.intellij.openapi.actionSystem.ex.ActionUtil$1.run(ActionUtil.java:199)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAware(ActionUtil.java:215)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher$1.performAction(IdeKeyEventDispatcher.java:587)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.lambda$processAction$2(IdeKeyEventDispatcher.java:634)
	at com.intellij.openapi.application.TransactionGuardImpl.performUserActivity(TransactionGuardImpl.java:204)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.processAction(IdeKeyEventDispatcher.java:633)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.inInitState(IdeKeyEventDispatcher.java:477)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.dispatchKeyEvent(IdeKeyEventDispatcher.java:211)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:657)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:391)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

```

### PR DESCRIPTION
**Pull request by KronicDeth**
Fixes #546

# Changelog
## Bug FIxes
* `CallDefinitionClause` completion provider is unexpectedly invoked both when `.` is typed, but continues to be invoked after a letter is typed after the `.`; however, once the letter is typed, the letter becomes the default prefix instead, so the prefix should only be reset to `""` when it ends in `.`.
* Disable `Callable#getVariants` unless `Unqualified` to  prevents local functions and macros being shown as completions for qualified names.

### CODE REVIEW

File: src/org/elixir_lang/reference/Callable.java [hunk 1]
```diff
@@ -10,6 +12,7 @@
 import com.intellij.usageView.UsageViewShortNameLocation;
 import com.intellij.usageView.UsageViewTypeLocation;
 import com.intellij.util.IncorrectOperationException;
+import com.intellij.util.ProcessingContext;
```
Comment (KronicDeth) [inline src/org/elixir_lang/reference/Callable.java]: These are used for the javadoc

File: src/org/elixir_lang/reference/Callable.java [hunk 2]
```diff
@@ -1,6 +1,8 @@
 package org.elixir_lang.reference;
 
 import com.google.common.collect.Sets;
+import com.intellij.codeInsight.completion.CompletionParameters;
```
Comment (KronicDeth) [inline src/org/elixir_lang/reference/Callable.java]: These are used for the javadoc

File: src/org/elixir_lang/reference/Callable.java [hunk 3]
```diff
@@ -1,6 +1,8 @@
...
+import com.intellij.codeInsight.completion.CompletionResultSet;
```
Comment (KronicDeth) [inline src/org/elixir_lang/reference/Callable.java]: These are used for the javadoc
