### PR TITLE
Don't type highlight BracketOperations

### LINKED ISSUE #471: Cannot highlight types for ElixirMatchedBracketOperation
# Version

4.5.0

# Exception

## Message

Cannot highlight types

### Excerpt

```
@callback list(query_options) :: {}[struct]

```
 Line(s) 85-85

### Element Class Name

```
org.elixir_lang.psi.impl.ElixirMatchedBracketOperationImpl
```

## Stacktrace

```
org.elixir_lang.errorreport.Logger.error(Logger.java:47)
org.elixir_lang.errorreport.Logger.error(Logger.java:30)
org.elixir_lang.annonator.ModuleAttribute.error(ModuleAttribute.java:145)
org.elixir_lang.annonator.ModuleAttribute.cannotHighlightTypes(ModuleAttribute.java:141)
org.elixir_lang.annonator.ModuleAttribute.highlightTypesAndTypeParameterUsages(ModuleAttribute.java:995)
org.elixir_lang.annonator.ModuleAttribute.highlightSpecification(ModuleAttribute.java:535)
org.elixir_lang.annonator.ModuleAttribute.highlightCallback(ModuleAttribute.java:162)
org.elixir_lang.annonator.ModuleAttribute.access$100(ModuleAttribute.java:37)
org.elixir_lang.annonator.ModuleAttribute$1.visitDeclaration(ModuleAttribute.java:93)
org.elixir_lang.annonator.ModuleAttribute$1.visitElement(ModuleAttribute.java:70)
com.intellij.psi.impl.PsiElementBase.accept(PsiElementBase.java:274)
org.elixir_lang.psi.impl.ElixirUnmatchedAtUnqualifiedNoParenthesesCallImpl.accept(ElixirUnmatchedAtUnqualifiedNoParenthesesCallImpl.java:38)
org.elixir_lang.annonator.ModuleAttribute.annotate(ModuleAttribute.java:53)
com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor.runAnnotators(DefaultHighlightVisitor.java:159)
com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor.visit(DefaultHighlightVisitor.java:102)
com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.runVisitors(GeneralHighlightingPass.java:340)
com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.access$100(GeneralHighlightingPass.java:64)
com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass$3.run(GeneralHighlightingPass.java:269)
com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.analyzeByVisitors(GeneralHighlightingPass.java:294)
com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.access$200(GeneralHighlightingPass.java:64)
com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass$4.run(GeneralHighlightingPass.java:300)
com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor.analyze(DefaultHighlightVisitor.java:86)
com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.analyzeByVisitors(GeneralHighlightingPass.java:297)
com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.collectHighlights(GeneralHighlightingPass.java:266)
com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.collectInformationWithProgress(GeneralHighlightingPass.java:205)
com.intellij.codeInsight.daemon.impl.ProgressableTextEditorHighlightingPass.doCollectInformation(ProgressableTextEditorHighlightingPass.java:97)
com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:67)
com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass$1$1.run(PassExecutorService.java:444)
com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1098)
com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass$1.run(PassExecutorService.java:435)
com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:452)
com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:402)
com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.doRun(PassExecutorService.java:432)
com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:408)
com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask.exec(JobLauncherImpl.java:204)
jsr166e.ForkJoinTask.doExec(ForkJoinTask.java:260)
jsr166e.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:858)
jsr166e.ForkJoinPool.scan(ForkJoinPool.java:1687)
jsr166e.ForkJoinPool.runWorker(ForkJoinPool.java:1642)
jsr166e.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:109)
```

### PR DESCRIPTION
**Pull request by KronicDeth**
Fixes #471

# Changelog
## Enhancements
* Failing regression test for #471

## Bug Fixes
* Don't type-highlight `BracketOperation`s as they occur when putting maps or structs in front of lists.

### CODE REVIEW

File: tests/org/elixir_lang/annotator/ModuleAttributeTest.java [hunk 1]
```diff
@@ -29,6 +29,11 @@ public void testIssue469() {
         myFixture.checkHighlighting(false, false, true);
     }
 
+    public void testIssue471() {
```
Comment (KronicDeth) [inline tests/org/elixir_lang/annotator/ModuleAttributeTest.java]: False issue: codacy can't detect that `checkHighlighting` contains asserts.
